# Generated by Django 4.1.7 on 2023-08-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stu_status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
