# Generated by Django 4.1.7 on 2023-08-03 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_myuser_stu_rollnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Review', models.TextField(max_length=500)),
                ('Stu_Foregin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
