# Generated by Django 4.1.7 on 2023-08-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_feeback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeback',
            name='Sentiment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
