# Generated by Django 4.1.7 on 2023-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stu_performance',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
