# Generated by Django 4.1.7 on 2023-08-02 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacherapp', '0002_assign_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_marks',
            name='Stu_foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
