# Generated by Django 4.1.7 on 2023-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_upload_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_marks',
            name='Sub_Grade',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
